# name: code coverage
# on: [push]
# jobs:
#   code-coverage-tests:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         redis-version: [6]
#     env:
#       TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
#       TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
#       TEST_CRC_TOKEN: ${{ secrets.TEST_CRC_TOKEN }}
#       TEST_CRC_RESPONSE: ${{ secrets.TEST_CRC_RESPONSE }}
#       PICKATRANDOM_SCREEN_NAME: ${{ secrets.PICKATRANDOM_SCREEN_NAME }}
#       PICKATRANDOM_USERID: ${{ secrets.PICKATRANDOM_USERID }}
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "14"
#       - uses: supercharge/redis-github-action@1.2.0
#         with:
#           redis-version: ${{ matrix.redis-version }}
#       - run: node -v
#       - run: yarn -v
#       # - run: redis-cli ping
#       - run: yarn install
#       - run: yarn test:codecov --detectOpenHandles
#       - run: bash <(curl -s https://codecov.io/bash) # Upload to Codecov
