name: sanity-check
on: [pull_request]
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn sanity-check
  tests:
    runs-on: ubuntu-latest
    env:
      TWITTER_CONSUMER_SECRET: "secret"
      TEST_CRC_TOKEN: "crc_token"
      TEST_CRC_RESPONSE: "sha256=gjiQ6uetgi4t5/+6PvFeAZ+idQ6rmuAfSEo3PnF6QV8="
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: node -v
      - run: yarn -v
      - run: yarn install
      - run: yarn build
